### PR TITLE
fix syntax error on endpoint

### PR DESCRIPTION
**Pull request by Tamiyadd**

### CODE REVIEW

**Comment by rossta** [comment]
@Tamiyadd Which ruby version are you using? 

Unless I'm mistaken, I don't believe this is a syntax error in ruby 2.1+. See #19 for more info.

**Comment by Tamiyadd** [comment]
Hi @rossta i'm using ruby 2.0.0-p247 :)

**Comment by rossta** [comment]
@Tamiyadd Thanks. As mentioned in #19, the currently supported ruby versions are 2.1+. Unless that changes, your best options are to either upgrade your Ruby version or support your own fork of webpush.

**Comment by Tamiyadd** [comment]
@rossta thanks for the answer, unfortunatelly my project is to big to switch to ruby 2.1. I think i will support my own fork of webpush.

thanks again

**Comment by zaru** [comment]
@Tamiyadd thanks for PR. Ruby2.0 support has ended.
If the upgrade is difficulty, I also think that the fork.

**Pull request closed without merging**
