### PR TITLE
Add some happy case specs

### PR DESCRIPTION
**Pull request by waheedel**

### CODE REVIEW

**Comment by zaru** [comment]
@waheedel Thanks for the pull-request. I wanted a test case. so happy!
However, it looks like this test case is not working.

Net::HTTP::Post raise
`<Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8>`

Random numbers may stub is not used in the cause.

**Comment by waheedel** [comment]
Hey @zaru great work on the gem.

I'm not seeing the error you provided. How are you running the tests?

**Comment by zaru** [comment]
@waheedel 
yes. the test passes all.
but `Webpush.payload_send` return false.

I can confirm to catch the exception that occurred in the `push_server_post`.

```
def push_server_post(endpoint, payload, api_key = "")
  begin
    uri = URI.parse(endpoint)
    # snip
    req = Net::HTTP::Post.new(uri.request_uri, header)
    req.body = payload[:ciphertext]
    res = http.request(req)
    return ("201" == res.code) ? true : false
  rescue => e
    p e # <Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8>
    return false
  end
end
```

I thought it was because the different `req.body` and `:expected_body`.
`req.body` will change every time run.

I am not familiar with how to use the webmock, please point out if I'm wrong.

**Comment by waheedel** [comment]
You are indeed right. Because we have a random salt the headers that we were expecting changed for each test. I have updated to stub out the `encrypt` method and return a predefined payload.

**Comment by zaru** [comment]
merged, very thanks!

**Comment by waheedel** [comment]
Thanks @zaru

**Pull request merged**
